


set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN P17 [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN P15 [get_ports {reset}]

set_property IOSTANDARD LVCMOS33 [get_ports {speaker}]
set_property PACKAGE_PIN H17 [get_ports {speaker}]

set_property IOSTANDARD LVCMOS33 [get_ports {t}]
set_property PACKAGE_PIN T1 [get_ports {t}]

set_property IOSTANDARD LVCMOS33 [get_ports {user_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_y[2]}]

set_property PACKAGE_PIN U3 [get_ports {user_y[0]}]
set_property PACKAGE_PIN U2 [get_ports {user_y[1]}]
set_property PACKAGE_PIN V2 [get_ports {user_y[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {choice_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choice_y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choice_y[2]}]

set_property PACKAGE_PIN V5 [get_ports {choice_y[0]}]
set_property PACKAGE_PIN V4 [get_ports {choice_y[1]}]
set_property PACKAGE_PIN R3 [get_ports {choice_y[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {mode_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_y[1]}]

set_property PACKAGE_PIN T3 [get_ports {mode_y[0]}]
set_property PACKAGE_PIN T5 [get_ports {mode_y[1]}]


set_property IOSTANDARD LVCMOS33 [get_ports {baDu_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {baDu_y[1]}]

set_property PACKAGE_PIN R15 [get_ports {baDu_y[0]}]
set_property PACKAGE_PIN R11 [get_ports {baDu_y[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {touch_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touch_y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touch_y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touch_y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touch_y[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touch_y[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touch_y[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touch_y[7]}]

set_property PACKAGE_PIN P5 [get_ports {touch_y[7]}]
set_property PACKAGE_PIN P4 [get_ports {touch_y[6]}]
set_property PACKAGE_PIN P3 [get_ports {touch_y[5]}]
set_property PACKAGE_PIN P2 [get_ports {touch_y[4]}]
set_property PACKAGE_PIN R2 [get_ports {touch_y[3]}]
set_property PACKAGE_PIN M4 [get_ports {touch_y[2]}]
set_property PACKAGE_PIN N4 [get_ports {touch_y[1]}]
set_property PACKAGE_PIN R1 [get_ports {touch_y[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {length_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {length_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {length_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {length_led[3]}]

set_property PACKAGE_PIN K1 [get_ports {length_led[0]}]
set_property PACKAGE_PIN H6 [get_ports {length_led[1]}]
set_property PACKAGE_PIN H5 [get_ports {length_led[2]}]
set_property PACKAGE_PIN J5 [get_ports {length_led[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property PACKAGE_PIN F6 [get_ports {led[7]}]
set_property PACKAGE_PIN G4 [get_ports {led[6]}]
set_property PACKAGE_PIN G3 [get_ports {led[5]}]
set_property PACKAGE_PIN J4 [get_ports {led[4]}]
set_property PACKAGE_PIN H4 [get_ports {led[3]}]
set_property PACKAGE_PIN J3 [get_ports {led[2]}]
set_property PACKAGE_PIN J2 [get_ports {led[1]}]
set_property PACKAGE_PIN K2 [get_ports {led[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports tub_sel1]
set_property IOSTANDARD LVCMOS33 [get_ports tub_sel2]
set_property IOSTANDARD LVCMOS33 [get_ports tub_sel3]
set_property IOSTANDARD LVCMOS33 [get_ports tub_sel4]
set_property IOSTANDARD LVCMOS33 [get_ports tub_sel5]
set_property IOSTANDARD LVCMOS33 [get_ports tub_sel6]
set_property IOSTANDARD LVCMOS33 [get_ports tub_sel7]
set_property IOSTANDARD LVCMOS33 [get_ports tub_sel8]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[0]}]

set_property PACKAGE_PIN G2 [get_ports tub_sel1]
set_property PACKAGE_PIN C2 [get_ports tub_sel2]
set_property PACKAGE_PIN C1 [get_ports tub_sel3]
set_property PACKAGE_PIN H1 [get_ports tub_sel4]
set_property PACKAGE_PIN G1 [get_ports tub_sel5]
set_property PACKAGE_PIN F1 [get_ports tub_sel6]
set_property PACKAGE_PIN E1 [get_ports tub_sel7]
set_property PACKAGE_PIN G6 [get_ports tub_sel8]
set_property PACKAGE_PIN B4 [get_ports {tub_control1[7]}]
set_property PACKAGE_PIN A4 [get_ports {tub_control1[6]}]
set_property PACKAGE_PIN A3 [get_ports {tub_control1[5]}]
set_property PACKAGE_PIN B1 [get_ports {tub_control1[4]}]
set_property PACKAGE_PIN A1 [get_ports {tub_control1[3]}]
set_property PACKAGE_PIN B3 [get_ports {tub_control1[2]}]
set_property PACKAGE_PIN B2 [get_ports {tub_control1[1]}]
set_property PACKAGE_PIN D5 [get_ports {tub_control1[0]}]
set_property PACKAGE_PIN D4 [get_ports {tub_control2[7]}]
set_property PACKAGE_PIN E3 [get_ports {tub_control2[6]}]
set_property PACKAGE_PIN D3 [get_ports {tub_control2[5]}]
set_property PACKAGE_PIN F4 [get_ports {tub_control2[4]}]
set_property PACKAGE_PIN F3 [get_ports {tub_control2[3]}]
set_property PACKAGE_PIN E2 [get_ports {tub_control2[2]}]
set_property PACKAGE_PIN D2 [get_ports {tub_control2[1]}]
set_property PACKAGE_PIN H2 [get_ports {tub_control2[0]}]